In [1]:
l1=[5,4,3,2,1]
l2=[9,8,7,6,5]
a=l1+l2
print(a)
print(type(a))

[5, 4, 3, 2, 1, 9, 8, 7, 6, 5]
<class 'list'>


In [2]:
import numpy as np
list1 = np.array([6,3,0,4,8])
print(list1)
# Accessing elements
print(list1[2])
# Slicing
print(list1[1:4])


[6 3 0 4 8]
0
[3 0 4]


In [3]:
import numpy as np
l1=[4,5,0,1,2]
l2=[3,2,7,8,9]
a=np.array(l1)
b=np.array(l2)
print(a+b)
print(type(a+b))

[ 7  7  7  9 11]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
a=[[9,8,7],[6,5,4],[3,2,1]]
b=[[1,2,3],[4,5,6],[7,8,9]]
c=np.array(a)
d=np.array(b)
print(c+d)
#multiplication
e=np.matmul(a,b)
print(e)
f=np.power(a,b)
print(f)
g=np.divide(a,b)
print(g)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]
[[   9   64  343]
 [1296 3125 4096]
 [2187  256    1]]
[[9.         4.         2.33333333]
 [1.5        1.         0.66666667]
 [0.42857143 0.25       0.11111111]]


In [5]:
app=[4,8,2,1,3]
s=np.sin(app)
print(s)
t=np.log(app)
print(t)
u=np.log2(app)
print(u)
v=np.exp(app)
print(v)

[-0.7568025   0.98935825  0.90929743  0.84147098  0.14112001]
[1.38629436 2.07944154 0.69314718 0.         1.09861229]
[2.        3.        1.        0.        1.5849625]
[5.45981500e+01 2.98095799e+03 7.38905610e+00 2.71828183e+00
 2.00855369e+01]
